name: Container Registry Cleanup

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  cleanup:
    name: Cleanup old container images
    runs-on: ubuntu-latest

    steps:
      - name: Delete old container images
        uses: actions/delete-package-versions@v5
        with:
          package-name: gerald-portfolio-chatbot
          package-type: container
          min-versions-to-keep: 10
          delete-only-untagged-versions: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
